library(readr)
library(pinyin)
library(magrittr)
library(tidyverse)
library(tibble)
library(stringr)
library(naniar)

# Greg:
# It'll be friendlier to run on multiple systems if we omit this line
# Then when you start a project, choose Set Working Directory To Source File Location
# setwd("/Users/liuxi/Desktop/Project/try_sh+sd+js")

# Read Files
engdata= read_csv('sh+sd+js_engdata.csv')
full_pyadmindiv = read_csv('full_pyadmindiv.csv')

## _engdata = English dataset
## _pyadmindiv = pinyin administrative divisions

# Greg:
# Please comment each code block, explaining its purpose

# Read English factory data
engdata = mutate(engdata, ftyaddrlow = tolower(engdata$ftyaddr))

# Greg: Coding style notes
# Preferable to have spaces surrounding = for readability
# Also spaces between arugments to a function
# See https://style.tidyverse.org/
# I've made some style edits 
# 'stylyr' package might help re-style the code

# Add empty prefecture and county columns
engdata = mutate(engdata,
                 prefecture = NA,
                 county = NA,
                 county_greg = NA,
                 prefecture_greg = NA)



# Greg:
# Following block assumes 'engdata' contains the var 'province'
# Note that the raw English factory data does not contain 'province' 
# 'province' must be generated by analyzing 'ftyaddr'

# Prefecture match -- collapsed name (e.g. "Beijing")
# For each English address...
for (add in 1:length(engdata$ftyaddrlow)) {
  
  # ...get admin divisions in relevant province
  specific_prov = filter(full_pyadmindiv, province_c==engdata$province[add]);

  # For each prefecture in that prov, try to match address string
  for (j in specific_prov$prefecture_c){
    if (isTRUE(grepl(j, engdata$ftyaddrlow[add]))){
      engdata$prefecture[add] = j
    }
  }
}

# Greg:
# Just curious: Why use isTRUE() in the final loop?
# grepl() already returns a logical
# The one advantage seems to be that isTRUE() handles NAs better

# Greg:
# We will need to be careful on overmatching in the above

# Prefecture match -- separated name (e.g. "Bei jing")
for (add in 1:length(engdata$ftyaddrlow)){
  specific_prov_s = filter(full_pyadmindiv, province_c == engdata$province[add]);
  for (j in specific_prov$prefecture_s){
    if (isTRUE(grepl(j,engdata$ftyaddrlow[add]))){
      engdata$prefecture[add]=j
    }
  }
}

# Greg:
# If you've already matched a prefecture above,
# we don't need to look in the entire province for counties
# We can instead look only inside that prefecture.


# County match - collapsed name ("linzi")
for (add in 1:length(engdata$ftyaddrlow)){
  specific_prov=filter(full_pyadmindiv,province_c==engdata$province[add]);
  for (j in specific_prov$county_c){
    if (isTRUE(grepl(j,engdata$ftyaddrlow[add]))){
      engdata$county[add]=j
    }
  }
}

# County match - spaced name ("lin zi")
for (add in 1:length(engdata$ftyaddrlow)){
  specific_prov=filter(full_pyadmindiv,province_c==engdata$province[add]);
  for (j in specific_prov$county_s){
    if (isTRUE(grepl(j,engdata$ftyaddrlow[add]))){
      engdata$county[add]=j
    }
  }
}

# Greg: 
# The four blocks above are great examples of duplicated code.
# Matching is the same except for the strings being matched
# Duplicated code (a) makes it harder to see similarity
#                 (b) makes it take longer to change later
# Why not write a single match function...
# ... then call it 4 times with 4 different arguments?

# Here's an example below, with some logic to only match each jurisdiction once

# Define a generic matching function
area_matcher = function(address, area_names) {
  for (i in 1:length(area_names)) {
     if (isTRUE(grepl(area_names[i], address))) {
       return(area_names[i]) 
     }
  }
  return(NA)
}

# Matching with the function
# Loop over all addresses
for (add in 1:length(engdata$ftyaddrlow)) {

  specific_prov = filter(full_pyadmindiv, province_c == engdata$province[add]);
  my_add = engdata$ftyaddrlow[add]
  
  # Prefectures - first collapsed 'beijing'
  engdata$prefecture_greg[add] = area_matcher(my_add,
                                              specific_prov$prefecture_c)
  # ...then with space 'bei jing' (if no match yet)
  if (is.na(engdata$prefecture_greg[add])) {
    engdata$prefecture_greg[add] = area_matcher(my_add,
                                                specific_prov$prefecture_s)
  }
  
  # Counties - first collapsed ('xicheng')
  engdata$county_greg[add] = area_matcher(my_add,
                                          specific_prov$county_c)
  # ...then with space 'xi cheng' (if no match yet)
  if (is.na(engdata$county_greg[add])) {
    engdata$county_greg[add] = area_matcher(my_add,
                                            specific_prov$county_s)
  }
}


write_csv(engdata,'output3prov.csv')
